---
title: "Decomposition of Neonatal Mortality in UP by Mother's Height"
author: "Nathan Franz"
date: "4/7/2020"
output: pdf_document
---

## The Question

Email 1

> The data you'd be using for the decomposition is the NFHS-2015 birth recode. 

> Could you please decompose the difference in NNM between UP and the rest of India by the mother's height (the mother's height variable in the birth recode, v438, needs to be divided by 10 to get height in cm; also please drop anyone who is less than 4.5 feet and more than 6 feet tall)?

> Could you please do this as a reweighting decomposition (which you'll learn about in the PhD class) where you ask: if the distribution of mothers' heights matched the distribution of heights in the rest of India, what would NNM be?

> Could you please also do this as a Kitagawa decomposition (which I think you already learned) where you ask: How much of the difference in NNM between UP and the rest of India can be explained by variation in NNM within height categories, and how much can be explained by differences in the distribution of height?

> Since this is sort of an exercise for now, maybe you could do it twice, using deciles and then centiles of height in cm?

> (The attached lpoly graph suggests that height doesn't explain it all -- although it will be interesting to see what the decomposition numbers say.  I'm also working on some analysis that looks specifically at adolescents, height, and NNM which is still puzzling me a bit.)

Email 2

> You can use deciles and centiles for both decompositions (with the kitawaga I think dean's class ended at a 2X3 but you could make that 2X10 or 2X100).  And hopefully it will be clear how to do it with the reweighting after Tuesday, but in case not, I'm happy to talk about it.

> As for which births to include - let's use the 5 years before the survey to match the published NNM statistics.  Even that is a little complicated though - because the survey took place over a period of about 18 months.  I am not remembering how they defined the look back period.  Could you please read the DHS report (you have have to consult other DHS methodology reports on mortality calculation) to figure it out and let me know?

## Sample Selection

There is a guide on how to calculate NNM here: <https://dhsprogram.com/data/Guide-to-DHS-Statistics/Early_Childhood_Mortality.htm>

## Reweighting Decomposition

## Kitagawa Decomposition

Referring to *Demography: Measuring and Modeling Population Processes* (2001) by Preston, Heuveline, and Guillot, we can write the equation for the Kitagawa decomposition in this case:

$$x^A - x^B = \sum_{i}\big(x_i^A - x_i^B\big)\Big(\frac{w_i^A + w_i^B}{2}\Big) + \sum_{i}\big(w_i^A - w_i^B\big)\Big(\frac{x_i^A + x_i^B}{2}\Big),$$
where $i$ indexes every quantile of mother's height for the whole sample, $A$ represents the sub-sample from Uttar Pradesh, $B$ represents the sub-sample from the rest of India, $x_i$ is the neonatal mortality rate for height quantile $i$, and $w_i$ is the proportion of the sample that is in height quantile $i$. The left term gives the amount of the difference in neonatal mortality due to differences in the NNM at each height quantile between Uttar Pradesh and the rest of India; the right term gives the amount due to differences between the height composition of Uttar Pradesh and the rest of India. 


## Results from and Comparison of the Two Methods

 Quantile   | Kitagawa - % Explained | Reweighting - % Explained
------------+------------------------+---------------------------
 Decile     | 9.1%                   | 6.7%
 Centile    | 9.3%                   | 7.1%




